name: h_tasksday
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  url_launcher: ^6.3.0
  flutter:
    sdk: flutter
  intl: ^0.19.0 # Пакет для работы с международным форматированием
  cupertino_icons: ^1.0.6 # Набор иконок, специфичных для iOS в стиле Cupertino
  flutter_slidable: ^3.1.0 # Библиотека для создания боковых панелей с возможностью свайпа
  isar: ^3.1.0+1 # Пакет для работы с базой данных Isar Database в Flutter
  isar_flutter_libs: ^3.1.0+1 #Расширение для Isar, предоставляющее дополнительные функции для работы с базой данных в Flutter
  path_provider: ^2.1.3 #Пакет для получения путей к директориям системы
  provider: #Пакет для управления состоянием в Flutter
  google_fonts: ^6.2.0 #Пакет для использования шрифтов Google Fonts в Flutter
  shared_preferences: ^2.2.3 #Пакет для работы с постоянным хранилищем на устройстве
  popover: ^0.3.0+1 #Библиотека для создания всплывающих окон в Flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
   
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  
flutter_launcher_icons:
  android: true 
  ios: true 
  image_path: "assets/images/logo.png"
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  min_sdk_android: 21 
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
